apiVersion: v1
kind: Service
metadata:
  name: vue-app
  labels:
    run: vue-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: vue-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-app
spec:
  selector:
    matchLabels:
      app: vue-app
  replicas: 2
  template:
    metadata:
      labels:
        run: vue-app
    spec:
      containers:
      - name: vue-app
        image: harounaouissaoui/vue-app:v1
        ports:
        - containerPort: 80
        - containerPort: 443
